title: Evan's Blog
description: >- 
  Welcome to the blog portion of my website! 
  This is where I share project writeups, tutorials, and notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.retrylife.ca"
root_url: "https://retrylife.ca"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax
highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-avatar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
